### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by mrandri19** [mossjacob/alfi-paper#1]
Hi, first of all thank you so much for providing the code of your paper.

I am interested in replicating the results from Lawrence et al., 2006 and I was looking at the implementation in https://github.com/anony-submissions/alfi/blob/main/notebooks/linear/exact.ipynb

It appears that some files are missing, in the notebook these imports are present:

```python
from alfi.models import ExactLFM
from alfi.trainers import ExactTrainer
from alfi.datasets import P53Data
from alfi.plot import Plotter1d
from alfi.utilities.data import p53_ground_truth
```

but in the [`alfi` folder](https://github.com/anony-submissions/alfi/tree/main/alfi) I can only find `datasets`, `kernels`, and `mcmc`. This means that `models`, `trainers`, `plot` and `utilities` are missing.

Could you help my find the rest of the code?

Thanks in advance,
Andrea

**Comment by mossjacob** [comment]
Hi Andrea, Thanks for pointing this out! I will update the README to point to the non-anonymous repository. This is the link:
https://github.com/mossjacob/alfi

That should contain all the files.

Best wishes,

Jacob

**Comment by mrandri19** [comment]
Amazing, and thanks for the instant response :)
